In [2]:
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

In [6]:
cap = cv.VideoCapture('video.mp4')
while(cap.isOpened()):
    ret,frame = cap.read()
    print(ret,frame)
    if ret == True:
        cv.imshow('Frame',frame)
        if cv.waitKey(25) & 0xFF == ord('q'):
            break
    else:
            break
cap.release()
cv.destroyAllWindows()

True [[[7 0 5]
  [7 0 5]
  [7 0 5]
  ...
  [7 0 5]
  [7 0 5]
  [7 0 5]]

 [[7 0 5]
  [7 0 5]
  [7 0 5]
  ...
  [7 0 5]
  [7 0 5]
  [7 0 5]]

 [[7 0 5]
  [7 0 5]
  [7 0 5]
  ...
  [7 0 5]
  [7 0 5]
  [7 0 5]]

 ...

 [[2 0 1]
  [2 0 1]
  [2 0 1]
  ...
  [2 0 1]
  [2 0 1]
  [2 0 1]]

 [[2 0 1]
  [2 0 1]
  [2 0 1]
  ...
  [2 0 1]
  [2 0 1]
  [2 0 1]]

 [[2 0 1]
  [2 0 1]
  [2 0 1]
  ...
  [2 0 1]
  [2 0 1]
  [2 0 1]]]
True [[[7 0 5]
  [7 0 5]
  [7 0 5]
  ...
  [7 0 5]
  [7 0 5]
  [7 0 5]]

 [[7 0 5]
  [7 0 5]
  [7 0 5]
  ...
  [7 0 5]
  [7 0 5]
  [7 0 5]]

 [[7 0 5]
  [7 0 5]
  [7 0 5]
  ...
  [7 0 5]
  [7 0 5]
  [7 0 5]]

 ...

 [[2 0 1]
  [2 0 1]
  [2 0 1]
  ...
  [2 0 1]
  [2 0 1]
  [2 0 1]]

 [[2 0 1]
  [2 0 1]
  [2 0 1]
  ...
  [2 0 1]
  [2 0 1]
  [2 0 1]]

 [[2 0 1]
  [2 0 1]
  [2 0 1]
  ...
  [2 0 1]
  [2 0 1]
  [2 0 1]]]
True [[[7 0 5]
  [7 0 5]
  [7 0 5]
  ...
  [7 0 5]
  [7 0 5]
  [7 0 5]]

 [[7 0 5]
  [7 0 5]
  [7 0 5]
  ...
  [7 0 5]
  [7 0 5]
  [7 0 5]]

 [[7 0 5]
  [7 0 5]
 

In [9]:
# cap = cv.VideoCapture('video.mp4')
cap = cv.VideoCapture(0)
# check if camera opened successfully

if(cap.isOpened()==False): 
    print("Error opening video file or camera")

while(cap.isOpened()):
    ret,frame = cap.read()
    print(ret,frame)
    if ret == True:
        cv.imshow('Frame',frame)
        if cv.waitKey(25) & 0xFF == ord('q'):
            break
    else:
        break
cap.release()
cv.destroyAllWindows()

True [[[105 106 104]
  [103 104 102]
  [103 104 102]
  ...
  [ 62  57  55]
  [ 62  57  54]
  [ 63  59  55]]

 [[105 106 103]
  [104 105 102]
  [103 104 101]
  ...
  [ 61  56  55]
  [ 62  57  55]
  [ 63  58  56]]

 [[104 106 103]
  [103 105 102]
  [103 105 102]
  ...
  [ 61  55  56]
  [ 61  55  55]
  [ 62  56  56]]

 ...

 [[ 20  19  26]
  [ 18  17  24]
  [ 14  14  21]
  ...
  [  0   0   2]
  [  0   0   1]
  [  0   0   1]]

 [[ 22  19  27]
  [ 19  16  24]
  [ 17  16  23]
  ...
  [  0   0   2]
  [  0   0   1]
  [  0   0   1]]

 [[ 20  17  26]
  [ 19  16  25]
  [ 17  15  24]
  ...
  [  0   0   2]
  [  0   0   1]
  [  0   0   1]]]
True [[[180 184 179]
  [178 182 177]
  [177 181 176]
  ...
  [128 123 124]
  [128 124 123]
  [128 124 123]]

 [[178 182 177]
  [178 182 177]
  [178 182 177]
  ...
  [127 122 123]
  [127 123 122]
  [128 124 122]]

 [[177 181 176]
  [178 182 177]
  [180 184 179]
  ...
  [128 125 124]
  [128 125 123]
  [130 127 123]]

 ...

 [[ 81  81  84]
  [ 76  76  79]
  [ 72  72

In [11]:
import os
cam =  cv.VideoCapture('video.mp4')
try:
    if not os.path.exists('data'):
        os.makedirs('data')

except OSError:
    print("Error: creating directory of data")

currentframe = 0

while(True):

    ret,frame = cam.read()

    if ret:
        name = './data/frame' + str(currentframe) + '.jpg'
        print ('Creating...'+ name)
        cv.imwrite(name,frame)
        currentframe += 1
    else:
        break
cam.release()
cv.destroyAllWindows()

Creating..../data/frame0.jpg
Creating..../data/frame1.jpg
Creating..../data/frame2.jpg
Creating..../data/frame3.jpg
Creating..../data/frame4.jpg
Creating..../data/frame5.jpg
Creating..../data/frame6.jpg
Creating..../data/frame7.jpg
Creating..../data/frame8.jpg
Creating..../data/frame9.jpg
Creating..../data/frame10.jpg
Creating..../data/frame11.jpg
Creating..../data/frame12.jpg
Creating..../data/frame13.jpg
Creating..../data/frame14.jpg
Creating..../data/frame15.jpg
Creating..../data/frame16.jpg
Creating..../data/frame17.jpg
Creating..../data/frame18.jpg
Creating..../data/frame19.jpg
Creating..../data/frame20.jpg
Creating..../data/frame21.jpg
Creating..../data/frame22.jpg
Creating..../data/frame23.jpg
Creating..../data/frame24.jpg
Creating..../data/frame25.jpg
Creating..../data/frame26.jpg
Creating..../data/frame27.jpg
Creating..../data/frame28.jpg
Creating..../data/frame29.jpg
Creating..../data/frame30.jpg
Creating..../data/frame31.jpg
Creating..../data/frame32.jpg
Creating..../data/fr

In [3]:
import os
cam =  cv.VideoCapture(0)
try:
    if not os.path.exists('data'):
        os.makedirs('data')

except OSError:
    print("Error: creating directory of data")

currentframe = 0

while(True):

    ret,frame = cam.read()

    if ret:
        name = './data/frame' + str(currentframe) + '.jpg'
        print ('Creating...'+ name)
        cv.imwrite(name,frame)
        currentframe += 1

    else:
        break
cam.release()
cv.destroyAllWindows()

Creating..../data/frame0.jpg
Creating..../data/frame1.jpg
Creating..../data/frame2.jpg
Creating..../data/frame3.jpg
Creating..../data/frame4.jpg
Creating..../data/frame5.jpg
Creating..../data/frame6.jpg
Creating..../data/frame7.jpg
Creating..../data/frame8.jpg
Creating..../data/frame9.jpg
Creating..../data/frame10.jpg
Creating..../data/frame11.jpg
Creating..../data/frame12.jpg
Creating..../data/frame13.jpg
Creating..../data/frame14.jpg
Creating..../data/frame15.jpg
Creating..../data/frame16.jpg
Creating..../data/frame17.jpg
Creating..../data/frame18.jpg
Creating..../data/frame19.jpg
Creating..../data/frame20.jpg
Creating..../data/frame21.jpg
Creating..../data/frame22.jpg
Creating..../data/frame23.jpg
Creating..../data/frame24.jpg
Creating..../data/frame25.jpg
Creating..../data/frame26.jpg
Creating..../data/frame27.jpg
Creating..../data/frame28.jpg
Creating..../data/frame29.jpg
Creating..../data/frame30.jpg
Creating..../data/frame31.jpg
Creating..../data/frame32.jpg
Creating..../data/fr

: 